spring.application.name=spring-ai-help-desk
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/spring-ai?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#spring.ai.openai.base-url=http://localhost:12434/engines
spring.ai.openai.api-key=docker
spring.ai.openai.chat.options.model=smollm2:latest

